--CREATE DATABASE LojaSoares;
-- traço traço é usado para comentar --
-- UNIQUEIDENTIFIER - ELE IRA GERAR UMA ID UNIVERSAL
-- PRIMARY KEY - ELE VAI SER A CHAVE PRIMARIA
-- VARCHAR - ELE POSSIBILITA USAR STRING E LIMITA A QUANTIDADE DE CARACTERES
-- DECIMAL -- ELE POSSIBILITA USAR NUMEROS FLOAT E LIMITA A QUANTIDADE DE CASAS ANTES DA VIRGULA E DEPOIS
-- NOT NULL -- OBRIGA ELE TER ALGUM DADO 

USE LojaSoares;
	
CREATE TABLE Produtos(
	IdProduto UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	nomeProduto VARCHAR(100) NOT NULL,
	precoProduto DECIMAL(10,2) NOT NULL
	);
